<?php
/**
 * OCCI Blogs — Default Configuration
 *
 * This file defines defaults. Do NOT edit this file directly.
 * Override values in config/config.local.php (which is git-ignored).
 */

// Load local overrides first
if (file_exists(__DIR__ . '/config.local.php')) {
    require __DIR__ . '/config.local.php';
}

// -------------------------------------------------------
// Database
// -------------------------------------------------------
if (!defined('DB_HOST'))    define('DB_HOST',    'localhost');
if (!defined('DB_NAME'))    define('DB_NAME',    'occi_blogs');
if (!defined('DB_USER'))    define('DB_USER',    'root');
if (!defined('DB_PASS'))    define('DB_PASS',    '');
if (!defined('DB_CHARSET')) define('DB_CHARSET', 'utf8mb4');

// -------------------------------------------------------
// Paths & URLs
// -------------------------------------------------------
if (!defined('BASE_PATH')) define('BASE_PATH', dirname(__DIR__));

if (!defined('SITE_URL')) {
    $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $host   = $_SERVER['HTTP_HOST'] ?? 'localhost';
    define('SITE_URL', $scheme . '://' . $host);
}

if (!defined('UPLOAD_DIR')) define('UPLOAD_DIR', BASE_PATH . '/public/uploads');
if (!defined('UPLOAD_URL')) define('UPLOAD_URL', SITE_URL . '/public/uploads');

// -------------------------------------------------------
// Uploads
// -------------------------------------------------------
if (!defined('MAX_UPLOAD_BYTES')) define('MAX_UPLOAD_BYTES', 10 * 1024 * 1024); // 10 MB
if (!defined('THUMB_WIDTH'))      define('THUMB_WIDTH',  400);
if (!defined('THUMB_HEIGHT'))     define('THUMB_HEIGHT', 300);

if (!defined('ALLOWED_MIME_TYPES')) define('ALLOWED_MIME_TYPES', [
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',
    'image/svg+xml',
]);

// -------------------------------------------------------
// App
// -------------------------------------------------------
if (!defined('APP_VERSION')) define('APP_VERSION', '1.0.0');
if (!defined('APP_ENV'))     define('APP_ENV',     'production');
if (!defined('SESSION_NAME')) define('SESSION_NAME', 'occi_blogs_session');
if (!defined('POSTS_PER_PAGE')) define('POSTS_PER_PAGE', 10);
